Meta tweaks
gillstrom/dpn-cli pull request #1
Opened 2017-09-22 16:13 UTC by alonalon

Meta tweaks, Updated packages

2017-09-22 16:59 UTC, kevva requested changes

2017-09-22 16:59 UTC, kevva commented on cli.js
> +				res[el].forEach(dep => console.log(indentString(chalk.dim(dep), 6)));
I would rewrite this whole block to:

```js
for (const x of Object.entries(res)) {
	const name = x[0];
	const dependencies = x[1];

	console.log(chalk.bold(`${dependencies.length} ${figures.arrowRight} ${name}`));

	if (cli.flags.verbose) {
		for (const x of dependencies) {
			console.log(indentString(chalk.dim(x), 6));
		}
	}
}
```

2017-09-23 09:16 UTC, alonalon commented on cli.js
> +				res[el].forEach(dep => console.log(indentString(chalk.dim(dep), 6)));
👍

2017-09-23 10:38 UTC, kevva approved these changes

2017-09-23 10:46 UTC, merged